import BtnSuggestion from "@/components/button/btn-suggestion";
import QueryClientProvider from "@/context/react-query/QueryClientProvider";
import SessionWrapper from "@/lib/SessionWrapper";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL("http://localhost:3000"),
  keywords: ["Keyword 1", "Keyword 2"],
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={`${inter.variable} antialiased size-full`}>
          <NextTopLoader />
          <QueryClientProvider>{children}</QueryClientProvider>
          <BtnSuggestion />
        </body>
      </html>
    </SessionWrapper>
  );
}
